[package]
name = "day_1"
version = "0.1.0"
authors = ["koleesch"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "day_1"
path = "src/lib.rs"

[dependencies]
